### ISSUE TITLE
Don't check input to not be an array.

### ISSUE THREAD

**Issue by koenhoeijmakers** [koenhoeijmakers/laravel-filterable#6]
Right now the [doFiltering method](https://github.com/koenhoeijmakers/laravel-filterable/blob/master/src/Filtering.php#L130) checks if the input is an array and if so, it doesn't apply the filters.

It would be better if the filtering doesn't bother with the "type" of this as any field that is "filterable" also needs to be validated against.

**Comment by robinvalk** [comment]
+1

**Comment by robinvalk** [comment]
Any ETA on this?? I'm really stuck atm

**Comment by robinvalk** [comment]
Can this also run on php 5.3?

**Comment by robinvalk** [comment]
Hi, it's been 11 hours and I have yet to receive a reply. Is this project still maintained??/?
